server:
  port: 8081

#mongodb
#spring:
#  data:
#    mongodb:
#      host: localhost
#      database: admin
#      port: 27017


#redis
spring:
  application:
    name: webflux
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 5000
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080